graph [
	node [ id 4 label "dd" ]
	node [ id 3 label "cc" ]
	node [ id 2 label "bb" ]
	node [ id 1 label "aa" ]
	edge [ source 4 target 3 weight 1 ]
	edge [ source 4 target 2 weight 0 ]
	edge [ source 4 target 1 weight 0 ]
	edge [ source 3 target 4 weight 0 ]
	edge [ source 3 target 3 weight 0 ]
	edge [ source 3 target 2 weight 1 ]
	edge [ source 3 target 1 weight 1 ]
	edge [ source 2 target 3 weight 1 ]
	edge [ source 2 target 1 weight 0 ]
	edge [ source 1 target 4 weight 1 ]
	edge [ source 1 target 3 weight 0 ]
	edge [ source 1 target 2 weight 0 ]
	edge [ source 1 target 1 weight 1 ]
]
