graph [
	sparse 0
	node [ id 1 label "aa" ]
	node [ id 2 label "bb" ]
	node [ id 3 label "cc" ]
	node [ id 4 label "dd" ]
	edge [ source 1 target 1 weight 1 ]
	edge [ source 1 target 4 weight 1 ]
	edge [ source 2 target 2 weight NA ]
	edge [ source 2 target 3 weight 1 ]
	edge [ source 2 target 4 weight NA ]
	edge [ source 3 target 1 weight 1 ]
	edge [ source 3 target 2 weight 1 ]
	edge [ source 4 target 3 weight 1 ]
	edge [ source 4 target 4 weight NA ]
]
