#!/bin/bash

tag=$1
shift
train=$1
shift
test=$1
shift
if [ -z "$test" ]; then
    echo usage: $0 tag train test
    exit 1
fi

out="output/$(./scripts/datestamp)/"
mkdir -p $out
num_restarts=10
myout="$out/max/$restart"
mkdir -p $myout
opts="--restarts=$num_restarts"
/usr/bin/time -o $myout/$tag.systime ./src/bhcd/bhcd $opts "$@" -p $myout/$tag -t $test $train

