#!/usr/bin/python

import sys, subprocess, os

def usage():
    print "config <debug|release>"
    sys.exit(1)

def main():
    if len(sys.argv) < 2:
        usage()

    mode = sys.argv[1]
    env = dict(os.environ)
    # -flto in cflags?
    env['CFLAGS'] = '-std=c99'
    # env['LDFLAGS'] = '-flto'
    env['CFLAGS'] += ' -D_FORIFY_SOURCE=2 -Wformat -Wformat-security'

    for mode in sys.argv[1:]:
        if mode == "debug":
            env['CFLAGS'] += ' -pedantic -Wall -Wfloat-equal -Wbad-function-cast -Wshadow -Wpointer-arith -Wcast-qual -Wstrict-prototypes -Wdeclaration-after-statement -Wuninitialized -Wstrict-overflow=5 -Wextra -Wno-unused-parameter -Wfatal-errors -Wwrite-strings'
            if 'CC' in env and env['CC'] != 'clang':
                # clang is slightly more aggressive, and finds soemthing glib..
                env['CFLAGS'] += ' -Wunreachable-code'
            # some of the above do not work without -O2
            env['CFLAGS'] += ' -ggdb3 '
        elif mode == "profile":
            env['CFLAGS'] += ' -pg -g '
        elif mode == "release":
            env['CFLAGS'] += ' -DG_DISABLE_ASSERT -O3'
        elif mode == "release":
            pass
        elif mode == 'portland':
	    env['CC'] = 'pgcc'
        elif mode == 'clang':
	    env['CC'] = 'clang'
        else:
            usage()

    subprocess.call(["make", "clean"])
    if subprocess.call(["./configure"], env=env):
        return
    subprocess.call(["make", "-j120"])

if __name__ == '__main__':
    main()

