#!/bin/bash

dd=$(./scripts/datestamp)
repeat='-R 1'
params=$repeat
params_sparse="-S $repeat"
#params_binsparse="-SB $repeat"

for mode in '' _sparse _binsparse
do
    params_name="params${mode}"
    pp=${!params_name}
    ./src/bhcd/bhcd $pp -v -p output/${dd}/nipsf${mode} data/nips-full.gml || exit 1
    ./scripts/bhcd_clusters output/${dd}/nipsf${mode}.tree output/${dd}/nipsf${mode}.fit output/${dd}/nipsf${mode}.cluster_tree || exit 1
    ./scripts/bhcd_plot_tree output/${dd}/nipsf${mode}.cluster_tree output/${dd}/nipsf${mode}.cluster_pdf || exit 1
done
