#!/bin/sh

opt='-R 100'
prefix="output/$(./scripts/datestamp)/football"

./src/bhcd $opt -p ${prefix} data/football.gml
./src/bhcd $opt -p ${prefix}_bin -B data/football.gml
./src/bhcd $opt -p ${prefix}_sparse -S data/football.gml
./src/bhcd $opt -p ${prefix}_binsparse -BS data/football.gml

for x in '' _bin _sparse _binsparse
do
    ./scripts/bhcd_plot $prefix$x.tree $prefix$x.fit $prefix$x.pdf
done
