#!/bin/sh

opt='-R 50 --data-symmetric'
prefix="output/$(./scripts/datestamp)/football"

./src/bhcd/bhcd $opt -p ${prefix} data/football.gml
./src/bhcd/bhcd $opt -p ${prefix}_bin -B data/football.gml
./src/bhcd/bhcd $opt -p ${prefix}_sparse -S data/football.gml
./src/bhcd/bhcd $opt -p ${prefix}_binsparse -BS data/football.gml
./src/bhcd/bhcd $opt -p ${prefix}_global -G data/football.gml
./src/bhcd/bhcd $opt -p ${prefix}_binglobal -BG data/football.gml

for x in '' _bin _sparse _binsparse _global _binglobal
do
    ./scripts/bhcd_plot $prefix$x.tree $prefix$x.fit $prefix$x.pdf
done
