#!/bin/sh

opt='-R 50'
prefix="output/$(./scripts/datestamp)/sampson_t4"

./src/bhcd/bhcd $opt -p ${prefix} data/pajek/Sampson_Sampson_T4.gml
./src/bhcd/bhcd $opt -p ${prefix}_bin -B data/pajek/Sampson_Sampson_T4.gml
./src/bhcd/bhcd $opt -p ${prefix}_sparse -S data/pajek/Sampson_Sampson_T4.gml
./src/bhcd/bhcd $opt -p ${prefix}_binsparse -BS data/pajek/Sampson_Sampson_T4.gml
./src/bhcd/bhcd $opt -p ${prefix}_global -G data/pajek/Sampson_Sampson_T4.gml
./src/bhcd/bhcd $opt -p ${prefix}_binglobal -GB data/pajek/Sampson_Sampson_T4.gml

for x in '' bin
do
    for y in '' sparse global
    do
        suffix=$x$y
        if [ ! -z "$suffix" ]
        then
            suffix=_$suffix
        fi
        ./scripts/bhcd_plot $prefix$suffix.tree $prefix$suffix.fit $prefix$suffix.pdf
    done
done

# ground truth: use any .fit file
./scripts/bhcd_plot data/sampson_t4_truth.tree $prefix.fit ${prefix}_truth.pdf
