#!/bin/bash -x

# for output
curdate=$(date +%Y%m%d)

search=""
if [ ! -z "$1" ]
then
    if [ "$1" = search ]
    then
        search=search
    else
        echo usage: $0 '[search]'
    fi
fi

for x in $(seq 1 10); do
    for c in nips gene; do
        tag=$c$x$search
        in_dir=output/latest/irm/$tag
        out_dir=output/$curdate/irm/$tag
        mkdir -p $out_dir
        echo $tag
        ./scripts/irm_pred -d latest -t $tag ${in_dir}_test/graph $out_dir/pred
        ./scripts/irm_pred -d latest -t $tag $in_dir/graph $out_dir/fit
    done
done
