#!/bin/bash

search=""
if [ ! -z "$1" ]
then
    if [ "$1" == "search" ]; then
        search=search
    else
        echo error: only argument can be search
    fi
fi

for x in $(seq 1 10); do
    ./scripts/irm_run gene$x$search data/ila/gene/gene_${x}_train.mat_train.gml data/ila/gene/gene_${x}_train.mat_test.gml &
    if [ $((($x-1) % 5)) == 4 ]; then
        wait; wait; wait; wait; wait
    fi
done
for x in $(seq 1 10); do
    ./scripts/irm_run nips$x$search data/ila/nips/nips_${x}_train.mat_train.gml data/ila/nips/nips_${x}_train.mat_test.gml &
    if [ $((($x-1) % 5)) == 4 ]; then
        wait; wait; wait; wait; wait
    fi
done
