#!/usr/bin/python2.7

import os,re

root = 'output'
latest_dir = os.path.join(root, 'latest')

looks_like_date = re.compile(r'^([0-9]+)([a-zA-Z0-9]*)$')

# make output/latest a link farm into the latest version of each file it can find.
def find_latest():
    latest = {}
    # traverse each output directory in date order
    dirs = os.listdir(root)
    dirs = filter(looks_like_date.match, dirs)
    dirs.sort(key=lambda path:
                (int(looks_like_date.match(path).group(1)), looks_like_date.match(path).group(2)),
                reverse=True)
    for date in dirs:
        # walk through the directory, updating latest
        dateprefix = os.path.join(root, date)
        for dateroot, datedirs, datefiles in os.walk(dateprefix):
            for datefile in datefiles:
                datefname = os.path.join(dateroot, datefile)
                fname = os.path.join(latest_dir, os.path.relpath(datefname, dateprefix))
                if fname not in latest:
                    latest[fname] = os.path.abspath(datefname)
    return latest

def remove_old(latest):
    for curroot, curdirs, curfiles in os.walk(latest_dir, topdown=False):
        # first go through and remove files not in latest
        for curfile in curfiles:
            fname = os.path.join(curroot, curfile)
            if not os.path.islink(fname):
                raise RuntimeError('WARNING: non-link '+fname)
            elif fname not in latest:
                print '-',fname
                os.remove(fname)
        # remove any empty directories
        for curdir in curdirs:
            dname = os.path.join(curroot, curdir)
            if not os.listdir(dname):
                print '-',dname
                os.rmdir(dname)

def update_links(latest):
    for fname in latest:
        dir = os.path.dirname(fname)
        if not os.path.exists(dir):
            os.makedirs(dir)
        if os.path.lexists(fname):
            if os.readlink(fname) != latest[fname]:
                print '~',fname
                os.remove(fname)
                os.symlink(latest[fname], fname)
        else:
            print '+',fname
            os.symlink(latest[fname], fname)

def main():
    latest = find_latest()
    print('latest has', len(latest), 'items. removing old...')
    remove_old(latest)
    print 'updating links...'
    update_links(latest)

if __name__ == '__main__':
    main()

