#!/usr/bin/python

import sys, os

def main():
	name = sys.argv[1]
	fname = os.path.basename(name)
	hname = fname.upper().replace('.','_')
	if os.path.exists(name):
		print 'ERROR:',name,'already exists'
		sys.exit(1)
	with open(name, 'w') as f:
		f.write("#ifndef\t"+hname+"\n")
		f.write("#define\t"+hname+"\n\n")
		f.write("#endif /*"+hname+"*/\n")

if __name__ == '__main__':
	main()

