#!/bin/bash

out="output/$(date '+%Y%m%d')/"
mkdir -p $out
num_restarts=10

for x in $(seq 1 10); do
    for name in nips gene; do
        train=data/ila/${name}/${name}_${x}_train.mat_train.gml
        test=data/ila/${name}/${name}_${x}_train.mat_test.gml

        for mode in blend max; do

            ./scripts/nrt_$mode ${name}${x} $train $test
            ./scripts/nrt_$mode ${name}${x}bin $train $test --binary-only
            ./scripts/nrt_$mode ${name}${x}sparse $train $test --sparse
            ./scripts/nrt_$mode ${name}${x}binsparse $train $test --binary-only --sparse
        done
    done
done
