#!/bin/bash

tag=$1
shift
train=$1
shift
test=$1
shift
if [ -z "$test" ]; then
    echo usage: $0 tag train test
    exit 1
fi

out="output/$(date '+%Y%m%d')/"
mkdir -p $out
num_restarts=50

for restart in $(seq $num_restarts); do
    echo restart $restart
    seed=$((restart+2828))
    myout="$out/blend/$restart"
    mkdir -p $myout
    opts="--restarts=1 --seed=$seed"
    /usr/bin/time -o $myout/$tag.systime ./src/fastnrt $opts "$@" -p $myout/$tag -t $test $train &
    if [ $(($restart % 5)) == 0 ]
    then
        wait
    fi
done
wait


