#!/usr/bin/python2.7

import sys
from math import *
from collections import defaultdict

# only look at the upper triangluar results.
upper_only = True

def logsumexp(xs):
    mm = max(xs)
    return mm + log(sum((exp(xx-mm) for xx in xs)))

def load(fname):
    truth = defaultdict(dict)
    lprob = defaultdict(dict)
    with open(fname) as pred:
        for line in pred.readlines():
            fields = [field.strip() for field in line.split(',')]
            if len(fields) == 6:
                time_taken, src, dst, correct, lp_false, lp_true = fields
            else:
                src, dst, correct, lp_false, lp_true = fields
                time_taken = 0.0
            if upper_only and src < dst:
                continue
            time_taken = float(time_taken)
            truth[time_taken][src, dst] = correct == "true"
            lprob[time_taken][src, dst] = { False: float(lp_false), True: float(lp_true) }
            acc = 1e-8
            #pred = lprob[time_taken][src,dst][True] > lprob[time_taken][src,dst][False]
            #pred = truth[time_taken][src,dst]
            #lprob[time_taken][src,dst][pred] = log(1.0 - acc)
            #lprob[time_taken][src,dst][not pred] = log(acc)
            #lprob[time_taken][src,dst][False] = log(0.5 + acc)
            #lprob[time_taken][src,dst][True] = log(0.5 - acc)
    return truth, lprob

def merge_preds(truthfiles, lprobfiles, blend=True):
    # increment time offset as we process each truth file.
    time_offset = 0.0

    # lprobs results we've seen so far; used for blending
    acc_lprobs = defaultdict(lambda: defaultdict(list))

    # make sure all truths are consistent so it doesn't matter which we pick.
    check_truths([truthfile[tt] for truthfile in truthfiles for tt in truthfile])
    truth0 = None

    lprobs = {}
    # process each file in turn
    for ii, truthfile in enumerate(truthfiles):
        file_time = 0
        # make sure in time order, so we can't cheat
        for time_taken in sorted(truthfile.keys(), key=lambda tt: float(tt)):
            truth = truthfile[time_taken]
            if truth0 is None:
                truth0 = truth
            lprob = lprobfiles[ii][time_taken]
            if blend:
                append_lprobs(acc_lprobs, lprob)
                lprob = blend_preds(acc_lprobs)
            lprobs[time_offset+time_taken] = lprob
            file_time += time_taken
        time_offset += file_time

    return truth0, lprobs

def append_lprobs(acc_lprobs, lprob):
    for src, dst in lprob.keys():
        acc_lprobs[src, dst][False].append(lprob[src, dst][False])
        acc_lprobs[src, dst][True].append(lprob[src, dst][True])

def blend_preds(acc_lprobs):
    lprob = defaultdict(lambda: defaultdict(float))
    for src, dst in acc_lprobs.keys():
        lprob[src, dst][False] = logmeanexp(acc_lprobs[src, dst][False])
        lprob[src, dst][True]  = logmeanexp(acc_lprobs[src, dst][True])
    return lprob

def check_truths(truths):
    truth0 = truths[0]
    for truth in truths[1:]:
        if truth != truth0:
            raise 'truth mismatch'

def check_sum(lprob):
    for kk in lprob:
        zz = logsumexp(lprob[kk].values())
        if zz > 1e-5:
            print kk, zz

def logmeanexp(xs):
    mx = max(xs)
    logn = log(len(xs))
    return mx + log(sum(exp(x-mx) for x in xs)) - logn

def mean(xs):
    return sum(xs)/float(len(xs))

def var(xs):
    mm = mean(xs)
    return sum((x*x for x in xs))/float(len(xs)) - mm*mm

def std(xs):
    return sqrt(max(0, var(xs)))

def std_err(xs):
    nn = len(xs)
    return std(xs)/sqrt(nn)

def avg_log_prob(truth, lprob):
    lp = []
    for src, dst in truth:
        lp.append(lprob[src, dst][truth[src, dst]])
    return mean(lp), std_err(lp)

def loss01(truth, lprob):
    total = 0.0
    wrong = 0.0
    for src, dst in truth:
        if upper_only and src < dst:
            continue
        total += 1.0
        call = max(lprob[src, dst].keys(), key=lambda kk: lprob[src,dst][kk])
        if call != truth[src, dst]:
            wrong += 1.0
    return wrong/total

def rmse(truth, lprob):
    se = []
    for src, dst in truth:
        if upper_only and src < dst:
            continue
        correct = 0.0
        if truth[src, dst]:
            correct = 1.0
        p = exp(lprob[src,dst][True])
        se.append(correct - 2*correct*p + p)
    return sqrt(mean(se))

def auc(truth, lprob):
    # number of links and non-links in truth
    nl = float(sum(truth.values()))
    nn = float(len(truth) - nl)
    assert(nl + nn == len(truth))
    # ri is the rank of the ith positive example
    So = 0.0
    sorted_k = sorted(truth.keys(), key=lambda kk: lprob[kk][True])
    for ii, kk in enumerate(sorted_k):
        if truth[kk]:
            So += ii+1

    return (So - (nl*(nl+1))/2)/(nl*nn)

def main():
    truthfiles = []
    lprobfiles = []
    for fname in sys.argv[1:]:
        truth, lprob = load(fname)
        truthfiles.append(truth)
        lprobfiles.append(lprob)

    truth, lprobs = merge_preds(truthfiles, lprobfiles)

    print 'time, lpred_mean, lpred_se, loss01, rmse, auc'
    for time_taken in sorted(lprobs.keys(), key=lambda tt: float(tt)):
        lprob = lprobs[time_taken]
        check_sum(lprob)
        lpred_mean, lpred_se = avg_log_prob(truth, lprob)
        print '%e, %e, %e,' % (time_taken, lpred_mean, lpred_se),
        print '%e, %e, %e' % (loss01(truth, lprob), rmse(truth, lprob), auc(truth, lprob))

if __name__ == '__main__':
    main()
