#!/bin/sh

cur=$(./scripts/datestamp)
mkdir -p output/$cur/blend

for type in pred fit
do
    for n in $(seq 1 10)
    do
        for c in gene nips
        do
            echo $c$n $type
            mkdir -p output/$cur/irm/$c$n
            mkdir -p output/$cur/irm/$c${n}search
#            ./scripts/pred output/latest/irm/$c${n}search/$type >output/$cur/irm/$c${n}search/score_$type &
#            ./scripts/pred output/latest/irm/$c$n/$type >output/$cur/irm/$c$n/score_$type &
            wait
            for x in "" sparse bin binsparse global binglobal
            do
                ./scripts/pred output/latest/blend/*/$c$n$x.$type >output/$cur/blend/$c$n$x.score_$type &
            done
            wait
        done
    done
done
