#!/bin/sh

cur=$(date +%Y%m%d)
mkdir -p output/$cur/blend

for type in pred fit
do
    for n in $(seq 1 10)
    do
        for c in nips gene
        do
            mkdir -p output/$cur/irm/$c$n
            mkdir -p output/$cur/irm/$c${n}search
            echo $c$n
            ./scripts/pred output/latest/irm/$c$n/$type >output/$cur/irm/$c$n/score_$type &
            ./scripts/pred output/latest/irm/$c${n}search/$type >output/$cur/irm/$c${n}search/score_$type &
            for x in "" sparse bin binsparse
            do
                ./scripts/pred output/latest/blend/*/$c$n$x.$type >output/$cur/blend/$c$n$x.score_$type &
            done
            for x in $(seq 6)
            do
                wait
            done
        done
    done
done
