#!/usr/bin/Rscript

library(ggplot2)

load_data <- function(name, fname) {
    print(paste('loading',name,'from',fname))
    fp <- file(paste(fname))
    dd <- read.csv(fp)
    return(cbind(name=name, dd))
}

data_index <- function(fold='nips1', fit_or_pred='pred') {
    return(data.frame(rbind(
        cbind('nrt',            paste('output/latest/blend/',fold,'.score_',fit_or_pred,sep='')),
        cbind('nrt-bin',        paste('output/latest/blend/',fold,'bin.score_',fit_or_pred,sep='')),
        cbind('nrt-sparse',     paste('output/latest/blend/',fold,'sparse.score_',fit_or_pred,sep='')),
        cbind('nrt-bin-sparse', paste('output/latest/blend/',fold,'binsparse.score_',fit_or_pred,sep='')),
        cbind('irm',        paste('output/latest/irm/',fold,'/score_',fit_or_pred, sep='')),
        cbind('irm-greedy', paste('output/latest/irm/',fold,'search/score_',fit_or_pred, sep=''))
        )))
}

mkplot <- function(dim, index=data_index()) {
    df = c()
    for (ii in 1:nrow(index)) {
        df = rbind(df, load_data(index[ii, 1], index[ii, 2]))
    }
    pp <- ggplot(df, aes_string(x='time', y=dim, color='name'))
    #pp <- ggplot(df, aes(x=time, y=auc, color=name))
    pp <- pp + geom_point() + geom_line()
    pp <- pp + scale_x_log10() + xlab('time') + ylab(dim)
    pp <- pp + guides(color = guide_legend(title='',nrow=3, direction='horizontal'))
    pp <- pp + theme(legend.position = 'top')

    return(pp)
}


main <- function() {
    for (type in c('pred', 'fit')) {
        for (field in c('lpred_mean','loss01','rmse','auc')) {
            for (fold in 1) {
                for (data in c('nips','gene')) {
                    foldname <- paste(data, fold, sep='')
                    print(paste(foldname,field))
                    pp <- mkplot(field, data_index(foldname,type))
                    ggsave(paste('output/plots/', foldname, '_', field, '_',type,'.pdf', sep=''), plot=pp)
                }
            }
        }
    }
}

main()
