#!/bin/sh
./src/fastnrt --lua data/blocks.gml <scripts/test.lua | \
    grep -v '^time:' | \
    diff -us - regress/blocks-lua.out && \
    ./scripts/leak --error-exitcode=1 ./src/fastnrt --lua data/blocks.gml <scripts/test.lua ||
    exit 1

