#!/usr/bin/python

import subprocess, datetime, sys

def main():
    leak_check = ['./scripts/leak', '--error-exitcode=1']
    tagname = datetime.datetime.now().strftime('tested-%Y%m%d%H%M%S')
    cmds = [
    # approx in order of run time
            ['./scripts/config', 'debug'],
            ['./src/test'],
            leak_check + ['./src/test'],
            ['./src/savetoy'],
            ['./scripts/tagtest_lua'],
            ['diff', '-u', 'regress/standard-toy3.gml', 'output/toy3.gml'],
            ['diff', '-u', 'regress/standard-toy4dense.gml', 'output/toy4dense.gml'],
            ['diff', '-u', 'regress/standard-toy4sparse.gml', 'output/toy4sparse.gml'],
            ['diff', '-u', 'regress/standard-toy3.adj', 'output/toy3.adj'],
            ['diff', '-u', 'regress/standard-toy4dense.adj', 'output/toy4dense.adj'],
            ['diff', '-u', 'regress/standard-toy4sparse.adj', 'output/toy4sparse.adj'],
            ['./src/fastnrt', '-t', 'data/blocks.gml', 'data/noisy-blocks.gml'],
            ['diff', '-u', 'regress/standard-noisy-blocks.tree', 'output/out.tree'],
            ['diff', '-u', 'regress/standard-noisy-blocks.pred', 'output/out.pred'],
            ['diff', '-u', 'regress/standard-noisy-blocks.fit', 'output/out.fit'],
            ['./src/fastnrt', '-S', '-t', 'data/blocks.gml', 'data/noisy-blocks.gml'],
            ['diff', '-u', 'regress/standard-noisy-blocks-sparse.tree', 'output/out.tree'],
            ['diff', '-u', 'regress/standard-noisy-blocks.pred', 'output/out.pred'],
            ['diff', '-u', 'regress/standard-noisy-blocks.fit', 'output/out.fit'],
            leak_check + ['./src/loadgml', 'data/ila/gene/gene_1_train.mat_train.gml',
                    'write_gml', 'output/out.gml', 'output/out.adj'],
            ['diff', '-u', 'regress/standard-gene1.gml', 'output/out.gml'],
            ['diff', '-u', 'regress/standard-gene1.adj', 'output/out.adj'],
            leak_check + ['./src/fastnrt', '-t', 'data/noisy-blocks.gml', 'data/blocks.gml'],
            ['diff', '-u', 'regress/standard-blocks.tree', 'output/out.tree'],
            ['diff', '-u', 'regress/standard-blocks.fit', 'output/out.fit'],
            ['diff', '-u', 'regress/standard-blocks.pred', 'output/out.pred'],
            leak_check + ['./src/fastnrt', '-S', '-t', 'data/noisy-blocks.gml', 'data/blocks.gml'],
            ['diff', '-u', 'regress/standard-blocks-sparse.tree', 'output/out.tree'],
            ['diff', '-u', 'regress/standard-blocks-sparse.fit', 'output/out.fit'],
            ['diff', '-u', 'regress/standard-blocks-sparse.pred', 'output/out.pred'],
    # check git is cleanly commited
    # - update the index
            ['git', 'update-index', '-q', '--ignore-submodules', '--refresh'],
    # - check for unstaged changes
            ['git', 'diff-files', '--quiet', '--ignore-submodules', '--'],
    # - check for uncommited changes
            ['git', 'diff-index', '--quiet', '--ignore-submodules', 'HEAD', '--'],
            ['git','tag', tagname]
        ]
    for cmd in cmds:
        if subprocess.call(cmd):
            print 'FAILED', ' '.join(cmd)
            sys.exit(1)
    print 'SUCCESS!'
    sys.exit(0)

if __name__ == '__main__':
    main();

